style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/aegoroff/solv
options:
  commits:
    filters:
      Type:
        - feat
        - feat!
        - fix
        - perf
        - refactor
  commit_groups:
    title_maps:
      feat: Features
      feat!: Features (BREAKING CHANGE)
      improve: Improvements
      improve!: Improvements (BREAKING CHANGE)
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      refactor!: Code Refactoring (BREAKING CHANGE)
  header:
    pattern: "^([a-zA-Z!_]*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE