name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos-x64, macos-arm64, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macos-x64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: macos-arm64
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
          - build: windows
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc

    steps:
      - name: Update rust
        run: rustup update
      - uses: actions/checkout@v4
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.target }}
          toolchain: stable
          args: "--workspace --release"
          strip: true
      - name: Run cargo-tarpaulin
        if: matrix.build == 'linux'
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.15.0"
          args: "--workspace -- --test-threads 1"
      - name: Upload to codecov.io
        if: matrix.build == 'linux'
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests
        if: matrix.build != 'linux'
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.target }}
          toolchain: stable
          args: "--workspace --release"
      - name: Run linter
        if: matrix.build == 'linux'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --release -- -Dwarnings
      - name: Run audit
        if: matrix.build == 'linux'
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
